using DRIT.Spreadsheet;
using DRIT.Spreadsheet.Examples.Shared;

var workbook = new Workbook();
var worksheet = workbook.Worksheets[0];
worksheet.Name = "Report";
worksheet.GetRange("A1:C1").SetValue(new[] { "Name", "Region", "Revenue" });
worksheet.GetRange("A2:A4").SetValue(new[] { "Atlas", "Meridian", "Orion" });
worksheet.GetRange("B2:B4").SetValue(new[] { "West", "East", "North" });
worksheet.GetRange("C2:C4").SetValue(new[] { 1200, 1800, 950 });
worksheet.Merge("A6:C6");
worksheet["A6"].Value = "Generated by DRIT.Spreadsheet";
var path = ExampleSupport.OutputPath("Writing.xlsx");
workbook.SaveAs(path);

var loaded = new Workbook(path);
ExampleSupport.Require((string)loaded.Worksheets[0]["A3"].Value == "Meridian", "Array data was not written.");
ExampleSupport.Require((double)loaded.Worksheets[0]["C4"].Value == 950.0, "Numeric array data was not written.");
ExampleSupport.ReportRoundTrip(path, loaded);
Console.WriteLine($"Wrote {loaded.Worksheets[0]["A1"].Value}, {loaded.Worksheets[0]["B1"].Value}, {loaded.Worksheets[0]["C1"].Value}");